# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\Gramatica.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_grammar(object):
    def setupUi(self, grammar):
        grammar.setObjectName("grammar")
        grammar.resize(594, 447)
        grammar.setMinimumSize(QtCore.QSize(594, 447))
        grammar.setMaximumSize(QtCore.QSize(594, 447))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icon/icons/favicon.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        grammar.setWindowIcon(icon)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(grammar)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(10, 10, 571, 421))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_5 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label_5.setMaximumSize(QtCore.QSize(215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(24)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_3.addWidget(self.label_5)
        spacerItem = QtWidgets.QSpacerItem(69, 10, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_3.addItem(spacerItem)
        self.label_6 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label_6.setWordWrap(True)
        self.label_6.setOpenExternalLinks(True)
        self.label_6.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByMouse)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_3.addWidget(self.label_6)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.grammarCloseBtn_2 = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.grammarCloseBtn_2.setObjectName("grammarCloseBtn_2")
        self.horizontalLayout_2.addWidget(self.grammarCloseBtn_2)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3.addLayout(self.verticalLayout_3)

        self.retranslateUi(grammar)
        QtCore.QMetaObject.connectSlotsByName(grammar)

    def retranslateUi(self, grammar):
        _translate = QtCore.QCoreApplication.translate
        grammar.setWindowTitle(_translate("grammar", "Acerca de la Gramática"))
        self.label_5.setText(_translate("grammar", "<html><head/><body><p><span style=\" font-size:12pt;\">Gramática utilizada:</span></p></body></html>"))
        self.label_6.setText(_translate("grammar", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2,sans-serif\'; font-size:10pt;\">El objetivo de este programa es implementar un analizador léxico y uno sintáctico, de modo que a partir de una entrada de números (base 10) pueda obtenerse una salida convirtiendo a distintas bases y a su vez mostrarse los tokens, el resultado y el árbol.</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2,sans-serif\'; font-size:10pt;\">La gramática a utilizar es:</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'MS Shell Dlg 2,sans-serif\'; font-size:10pt;\"><br /></p>\n"
"<table border=\"1\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px;\" cellspacing=\"0\" cellpadding=\"0\">\n"
"<tr>\n"
"<td style=\" padding-left:0; padding-right:0; padding-top:0; padding-bottom:0;\">\n"
"<p align=\"center\" style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2,sans-serif,serif\'; font-size:10pt;\">Operador</span> </p></td>\n"
"<td style=\" padding-left:0; padding-right:0; padding-top:0; padding-bottom:0;\">\n"
"<p align=\"center\" style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2,sans-serif,serif\'; font-size:10pt;\">Ejemplo</span> </p></td>\n"
"<td style=\" padding-left:0; padding-right:0; padding-top:0; padding-bottom:0;\">\n"
"<p align=\"center\" style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2,sans-serif,serif\'; font-size:10pt;\">Resultado</span> </p></td>\n"
"<td style=\" padding-left:0; padding-right:0; padding-top:0; padding-bottom:0;\">\n"
"<p align=\"center\" style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2,sans-serif,serif\'; font-size:10pt;\">Descripción</span> </p></td></tr>\n"
"<tr>\n"
"<td style=\" padding-left:0; padding-right:0; padding-top:0; padding-bottom:0;\">\n"
"<p align=\"center\" style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2,sans-serif,serif\'; font-size:10pt;\">hex</span> </p></td>\n"
"<td style=\" padding-left:0; padding-right:0; padding-top:0; padding-bottom:0;\">\n"
"<p align=\"center\" style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2,sans-serif,serif\'; font-size:10pt;\">403hex</span> </p></td>\n"
"<td style=\" padding-left:0; padding-right:0; padding-top:0; padding-bottom:0;\">\n"
"<p align=\"center\" style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2,sans-serif,serif\'; font-size:10pt;\">hex_193</span> </p></td>\n"
"<td style=\" padding-left:0; padding-right:0; padding-top:0; padding-bottom:0;\">\n"
"<p align=\"center\" style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2,sans-serif,serif\'; font-size:10pt;\">Convierte a hexadecimal</span> </p></td></tr>\n"
"<tr>\n"
"<td style=\" padding-left:0; padding-right:0; padding-top:0; padding-bottom:0;\">\n"
"<p align=\"center\" style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2,sans-serif,serif\'; font-size:10pt;\">oct</span> </p></td>\n"
"<td style=\" padding-left:0; padding-right:0; padding-top:0; padding-bottom:0;\">\n"
"<p align=\"center\" style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2,sans-serif,serif\'; font-size:10pt;\">403oct</span> </p></td>\n"
"<td style=\" padding-left:0; padding-right:0; padding-top:0; padding-bottom:0;\">\n"
"<p align=\"center\" style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2,sans-serif,serif\'; font-size:10pt;\">oct_623</span> </p></td>\n"
"<td style=\" padding-left:0; padding-right:0; padding-top:0; padding-bottom:0;\">\n"
"<p align=\"center\" style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2,sans-serif,serif\'; font-size:10pt;\">Convierte a octal</span> </p></td></tr>\n"
"<tr>\n"
"<td style=\" padding-left:0; padding-right:0; padding-top:0; padding-bottom:0;\">\n"
"<p align=\"center\" style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2,sans-serif,serif\'; font-size:10pt;\">rom</span> </p></td>\n"
"<td style=\" padding-left:0; padding-right:0; padding-top:0; padding-bottom:0;\">\n"
"<p align=\"center\" style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2,sans-serif,serif\'; font-size:10pt;\">403rom</span> </p></td>\n"
"<td style=\" padding-left:0; padding-right:0; padding-top:0; padding-bottom:0;\">\n"
"<p align=\"center\" style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2,sans-serif,serif\'; font-size:10pt;\">rom_CDIII</span> </p></td>\n"
"<td style=\" padding-left:0; padding-right:0; padding-top:0; padding-bottom:0;\">\n"
"<p align=\"center\" style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2,sans-serif,serif\'; font-size:10pt;\">Convierte a números romanos</span> </p></td></tr>\n"
"<tr>\n"
"<td style=\" padding-left:0; padding-right:0; padding-top:0; padding-bottom:0;\">\n"
"<p align=\"center\" style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2,sans-serif,serif\'; font-size:10pt;\">alt</span> </p></td>\n"
"<td style=\" padding-left:0; padding-right:0; padding-top:0; padding-bottom:0;\">\n"
"<p align=\"center\" style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2,sans-serif,serif\'; font-size:10pt;\">403alt</span> </p></td>\n"
"<td style=\" padding-left:0; padding-right:0; padding-top:0; padding-bottom:0;\">\n"
"<p align=\"center\" style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2,sans-serif,serif\'; font-size:10pt;\">alt_</span> </p></td>\n"
"<td style=\" padding-left:0; padding-right:0; padding-top:0; padding-bottom:0;\">\n"
"<p align=\"center\" style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2,sans-serif,serif\'; font-size:10pt;\">Convierte a una base </span><span style=\" font-family:\'MS Shell Dlg 2,sans-serif,serif\'; font-size:10pt; color:#3f3f3f;\">a</span><span style=\" font-family:\'MS Shell Dlg 2,sans-serif,serif\'; font-size:10pt; color:#000000;\">lternativa</span><span style=\" font-family:\'MS Shell Dlg 2,sans-serif,serif\'; font-size:10pt; font-style:italic; color:#3f3f3f;\"> (Ver documentación)</span> </p></td></tr>\n"
"<tr>\n"
"<td style=\" padding-left:0; padding-right:0; padding-top:0; padding-bottom:0;\">\n"
"<p align=\"center\" style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2,sans-serif,serif\'; font-size:10pt;\">ran</span> </p></td>\n"
"<td style=\" padding-left:0; padding-right:0; padding-top:0; padding-bottom:0;\">\n"
"<p align=\"center\" style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2,sans-serif,serif\'; font-size:10pt;\">403ran</span> </p></td>\n"
"<td style=\" padding-left:0; padding-right:0; padding-top:0; padding-bottom:0;\">\n"
"<p align=\"center\" style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2,sans-serif,serif\'; font-size:10pt;\">hex_193</span> </p></td>\n"
"<td style=\" padding-left:0; padding-right:0; padding-top:0; padding-bottom:0;\">\n"
"<p align=\"center\" style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2,sans-serif,serif\'; font-size:10pt;\">Convierte a cualquiera de las anteriores de manera aleatoria</span> </p></td></tr></table>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.grammarCloseBtn_2.setText(_translate("grammar", "Cerrar"))

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    grammar = QtWidgets.QDialog()
    ui = Ui_grammar()
    ui.setupUi(grammar)
    grammar.show()
    sys.exit(app.exec_())
