# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\tree.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Arbol(object):
    def setupUi(self, Arbol):
        self.n = 0
        Arbol.setObjectName("Arbol")
        Arbol.resize(800, 600)
        Arbol.setMinimumSize(QtCore.QSize(800, 600))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icon/icons/favicon.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Arbol.setWindowIcon(icon)
        self.verticalLayout = QtWidgets.QVBoxLayout(Arbol)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tree = QtWebEngineWidgets.QWebEngineView(Arbol)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tree.sizePolicy().hasHeightForWidth())
        self.tree.setSizePolicy(sizePolicy)
        self.tree.setMinimumSize(QtCore.QSize(750, 500))
        self.tree.setObjectName("tree")
        self.verticalLayout.addWidget(self.tree)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.svgBtn = QtWidgets.QPushButton(Arbol)
        self.svgBtn.setStyleSheet("")
        self.svgBtn.setObjectName("svgBtn")
        self.horizontalLayout.addWidget(self.svgBtn)
        self.pngBtn = QtWidgets.QPushButton(Arbol)
        self.pngBtn.setObjectName("pngBtn")
        self.horizontalLayout.addWidget(self.pngBtn)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(Arbol)
        QtCore.QMetaObject.connectSlotsByName(Arbol)

    def retranslateUi(self, Arbol):
        _translate = QtCore.QCoreApplication.translate
        Arbol.setWindowTitle(_translate("Arbol", "Árbol Generado"))
        self.svgBtn.setText(_translate("Arbol", "Exportar como SVG..."))
        self.pngBtn.setText(_translate("Arbol", "Exportar como PNG..."))

    def download_requested(self, download):
        """
            Maneja las solicitudes de descarga
        """
        if self.n == 0:
            self.n +=1
            suffix = ""
            if download.url().toString().split(";")[0].split("/")[1] == "html":
                suffix = "svg"
            elif download.url().toString().split(";")[0].split("/")[1] == "png":
                suffix = "png"
            path, _ = QtWidgets.QFileDialog.getSaveFileName(
                self.tree, "Exportar arbol a ...", "arbol", "*." + suffix
            )
            if path:
                download.setPath(path)
                download.accept()
                download.finished.connect(self.download_finished)

    @staticmethod
    def download_finished():
        print("Archivo Descargado con exito")    

from PyQt5 import QtWebEngineWidgets


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Arbol = QtWidgets.QWidget()
    ui = Ui_Arbol()
    ui.setupUi(Arbol)
    Arbol.show()
    sys.exit(app.exec_())
